### ISSUE TITLE
Edit Job "master" fields.

### ISSUE THREAD

**Issue by KAMogler** [farm-entry/app#308]
Users would like to edit certain data fields on a Job from the APP (not set up new jobs, but edit existing jobs).   It would likely be under the "Account" menu as it would be accessed infrequently. 
User would select the Job from a drop-down and then could edit the following fields:
No
Description
Person_Responsible   (selection from Resources filter:type = Person) Resources (web services endpoint)
Supervisor (Project_Manager) (selection from UserID table)JobProjectManager (web services endpoint)
Status:
Starting_Date  (calendar selection)
Ending_Date (calendar selection)
Pig_Source_Flow

The APP would show the current values for these fields and would allow the user to edit (change).   
Micah - draw up a wire frame for this new APP page.

**Comment by KAMogler** [comment]
@mmogler This is a "next" priority after either Matt or Sergei is done with current assignments.  You may want to lay out a wireframe for this page.

**Comment by mmogler** [comment]
In order to do a PUT/PATCH operation you need to follow the below flow:

1. Perform a GET operation on then endpoint/table that you want to update
 - ex: GET/JobCard('2049X31W')
 2. In the response message you will grab the "@odata.etag" value
 - ex from Insomnia: "W/\"JzM2O3B3QUFBQUo3L3pJQU1BQTBBRGtBV0FBekFERUFWd0FBQUFBQTk7MTEwOTU0MzExMDsn\""
 3. Strip out the escape characters and the leading and ending quotes.
 - ex stripped: W/"JzM2O3B3QUFBQUo3L3pJQU1BQTBBRGtBV0FBekFERUFWd0FBQUFBQTk7MTEwOTU0MzExMDsn"
4. For your PUT/POST operations in the JSON, provide the fields you wish to updated
- ex: `{
              "Project_Manager": "REECE"
          }`
5. Add the following 3 fields in the header. Add the stripped out etag to the If-Match header
- ex: `Content-Type: application/json; Accept: application/json; If-Match: ${Insert stripped etag here}  `
6. etag will update any time a table has updated. Best practice will be always pull in etag via GET then strip out and use that etag for the PUT/PATCH operation.

**Comment by KAMogler** [comment]
Added a new field to User Endpoint to show User Group Code.   This menu Item should show up for users with User Group Code = 00APPTABLEUPDATE.   The menu item for "Table Edits" should only appear if user id associated with this User Group Code.

**Comment by mmogler** [comment]
Flow - https://www.figma.com/proto/M32Qds6b4cQYYXp3ufcX7w/dynamic-scorecard-wireframe?node-id=683%3A673&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=683%3A673&show-proto-sidebar=1

**Comment by KAMogler** [comment]
Added endpoint for filter of users who should "see this menu option.  UserTableUpdate  -the query has just one field the User IDs that are valid for this menu option.  They are specified in the User Group which is a filter for this query.
